<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class ServiceApplicationResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'plan_name' => $this->plan_name,
            'client_last_name' => $this->client_last_name,
            'client_first_name' => $this->client_first_name,
            'client_middle_name' => $this->client_middle_name,
            'client_gender' => $this->client_gender,
            'client_date_of_birth' => $this->client_date_of_birth,
            'client_home_address' => $this->client_home_address,
            'client_office_address' => $this->client_office_address,
            'client_phone_number' => $this->client_phone_number,
            'client_email' => $this->client_email,
            'applicant_id' => $this->applicant_id,
            'applicant' => new UserResource($this->applicant),
            'client' => new ClientChartResource($this->client),
            'phone_number_payee' => $this->phone_number_payee,
            'phone_number_next_of_kin' => $this->phone_number_next_of_kin,
            'primary_language_spoken' => $this->primary_language_spoken,
            'receiving_service_elsewhere' => $this->receiving_service_elsewhere,
            'home_settings_description' => $this->home_settings_description,
            'require_general_healthcare' => $this->require_general_healthcare,
            'require_mobility_assistance' => $this->require_mobility_assistance,
            'require_personal_supervision' => $this->require_personal_supervision,
            'require_emotional_support' => $this->require_emotional_support,
            'require_demantia_care' => $this->require_demantia_care,
            'require_grocery_shopping_assistance' => $this->require_grocery_shopping_assistance,
            'require_feeding_assistance' => $this->require_feeding_assistance,
            'require_haircare_nailcare_assistance' => $this->require_haircare_nailcare_assistance,
            'require_bathing_grooming_assistance' => $this->require_bathing_grooming_assistance,
            'require_dishes_laundry_assistance' => $this->require_dishes_laundry_assistance,
            'require_meal_prep_assistance' => $this->require_meal_prep_assistance,
            'require_toileting_assistance' => $this->require_toileting_assistance,
            'require_health_monitoring' => $this->require_health_monitoring,
            'require_vital_signs_monitoring' => $this->require_vital_signs_monitoring,
            'require_oral_skin_medication' => $this->require_oral_skin_medication,
            'require_injections' => $this->require_injections,
            'require_dressing_of_wounds' => $this->require_dressing_of_wounds,
            'require_oxygen_therapy' => $this->require_oxygen_therapy,
            'require_exercise_oral_feeding' => $this->require_exercise_oral_feeding,
            'require_ng_tube_feeding' => $this->require_ng_tube_feeding,
            'require_post_surgical_management' => $this->require_post_surgical_management,
            'require_companionship' => $this->require_companionship,
            'require_appointment_reminder' => $this->require_appointment_reminder,
            'require_patient_recovery_monitoring' => $this->require_patient_recovery_monitoring,
            'require_improvement_suggestions' => $this->require_improvement_suggestions,
            'require_improvement_advice' => $this->require_improvement_advice,
            'require_steady_availability_for_questions' => $this->require_steady_availability_for_questions,
            'require_highly_skilled_nursing' => $this->require_highly_skilled_nursing,
            'require_other_skilled_nursing' => $this->require_other_skilled_nursing,
            'require_other_assistance' => $this->require_other_assistance,
            'other_assistance_description' => $this->other_assistance_description,
            'main_source_of_finance' => $this->main_source_of_finance,
            'has_history_of_urinary_incontinence' => $this->has_history_of_urinary_incontinence,
            'has_history_of_feacal_incontinence' => $this->has_history_of_feacal_incontinence,
            'number_of_falls_past_12months' => $this->number_of_falls_past_12months,
            'has_diabetes' => $this->has_diabetes,
            'has_hypertension' => $this->has_hypertension,
            'has_hearing_impairment' => $this->has_hearing_impairment,
            'has_dental_problem' => $this->has_dental_problem,
            'has_stroke_tia' => $this->has_stroke_tia,
            'has_sleep_problem' => $this->has_sleep_problem,
            'has_arthritis' => $this->has_arthritis,
            'has_difficulty_moving_around' => $this->has_difficulty_moving_around,
            'has_blindness_or_partial' => $this->has_blindness_or_partial,
            'has_congestive_heart_failure' => $this->has_congestive_heart_failure,
            'has_history_of_demantia' => $this->has_history_of_demantia,
            'has_history_of_mental_illness' => $this->has_history_of_mental_illness,
            'has_cancer_or_terminal_illness' => $this->has_cancer_or_terminal_illness,
            'other_health_problems' => $this->other_health_problems,
            'admissions_in_last_1year' => $this->admissions_in_last_1year,
            'past_medical_surgical_history' => $this->past_medical_surgical_history,
            'all_current_medications' => $this->all_current_medications,
            'known_allergies' => $this->known_allergies,
            'weight_kg' => $this->weight_kg,
            'height_ft' => $this->height_ft,
            'build_slim_or_plum' => $this->build_slim_or_plum,
            'latest_blood_pressure' => $this->latest_blood_pressure,
            'latest_fasting_blood_sugar' => $this->latest_fasting_blood_sugar,
            'hiv_status' => $this->hiv_status,
            'hbsag_hcv_status' => $this->hbsag_hcv_status,
            'all_relevant_diagnosis' => $this->all_relevant_diagnosis,
            'signature' => $this->signature,
            'send_all_correspondence_to_applicant' => $this->send_all_correspondence_to_applicant,
            'service_cost' => $this->service_cost,
            'initial_payment_date' => $this->initial_payment_date,
            'date_approved' => $this->date_approved,
            'is_approved' => $this->is_approved,
            'fullname_next_of_kin' => $this->fullname_next_of_kin,
            'fullname_signatory' => $this->fullname_signatory,
            'require_basic_food_preparation' => $this->require_basic_food_preparation,
            'status' => $this->status,
            'client_state' => $this->client_state,
            'client_city' => $this->client_city,
            'disapproval_reason' => $this->disapproval_reason,
            'applying_for_self' => $this->applying_for_self,
            'relation_next_of_kin' => $this->relation_next_of_kin,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
}
