<?php

namespace App\Http\Resources;

use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Http\Resources\Json\JsonResource;

class StaffChartResource extends JsonResource
{
    use ResourceHelpers;


    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return $this->removeNullValues([
            'id' => $this->id,
            'staff_id' => $this->staff_id,
            'client_id' => $this->client_id,
            'type' => $this->type,
            'comment' => $this->comment,
            'report_date'  => $this->report_date,
            'report_time'  => $this->report_time,
            'risk_of_falls'  => $this->risk_of_falls,
            'is_red_flag'  => $this->is_red_flag,
            'media1'  => $this->media1,
            'media2'  => $this->media2,
            'media3'  => $this->media3,
            'media4'  => $this->media4,
            'category'  => $this->category,
            'health_issue'  => $this->health_issue,
            'cream_applied'  => $this->cream_applied,
            'consequence_event'  => $this->consequence_event,
            'location'  => $this->location,
            'reason_for_visit'  => $this->reason_for_visit,
            'resultant_action'  => $this->resultant_action,
            'is_age6069'  => $this->is_age6069,
            'is_age7079'  => $this->is_age7079,
            'is_age8089'  => $this->is_age8089,
            'is_age90_plus'  => $this->is_age90_plus,
            'movement_going_up_stairs'  => $this->movement_going_up_stairs,
            'movement_coming_down_stairs'  => $this->movement_coming_down_stairs,
            'suggested_equip_resident'  => $this->suggested_equip_resident,
            'suggested_equip_staff'  => $this->suggested_equip_staff,
            'any_safeguarding_issues'  => $this->any_safeguarding_issues,
            'risk_to_children'  => $this->risk_to_children,
            'risk_to_offending'  => $this->risk_to_offending,
            'any_other_areas_of_risk'  => $this->any_other_areas_of_risk,
            'dosage_afternoon_when'  => $this->dosage_afternoon_when,
            'dosage_evening'  => $this->dosage_evening,
            'dosage_evening_when'  => $this->dosage_evening_when,
            'dosage_afternoon'  => $this->dosage_afternoon,
            'reason_for_medication'  => $this->reason_for_medication,
            'other_intake_guide'  => $this->other_intake_guide,
            'is_morning_dose_administered'  => $this->is_morning_dose_administered,
            'is_afternoon_dose_administered'  => $this->is_afternoon_dose_administered,
            'is_evening_dose_administered'  => $this->is_evening_dose_administered,
            'start_date'  => $this->start_date,
            'is_positive_covid_19'  => $this->is_positive_covid_19,
            'weight_pounds'  => $this->weight_pounds,
            'use_kilogram'  => $this->use_kilogram,
            'description'  => $this->description,
            'result'  => $this->result,
            'score'  => $this->score,
            'drink_type'  => $this->drink_type,
            'delivery_method'  => $this->delivery_method,
            'quantity_ml'  => $this->quantity_ml,
            'level_of_need'  => $this->level_of_need,
            'present_situation'  => $this->present_situation,
            'actions'  => $this->actions,
            'family_participant'  => $this->family_participant,
            'other_participants'  => $this->other_participants,
            'resident_needs'  => $this->resident_needs,
            'weight_kg'  => $this->weight_kg,
            'review_date'  => $this->review_date,
            'risk_of_physical_abuse_to_self'  => $this->risk_of_physical_abuse_to_self,
            'risk_of_physical_abuse_to_others'  => $this->risk_of_physical_abuse_to_others,
            'risk_of_discrimination'  => $this->risk_of_discrimination,
            'risk_of_pressure_sores'  => $this->risk_of_pressure_sores,
            'risk_of_manual_handling'  => $this->risk_of_manual_handling,
            'risk_of_wandering'  => $this->risk_of_wandering,
            'risk_to_property'  => $this->risk_to_property,
            'agitation_verbal_physical_aggression'  => $this->agitation_verbal_physical_aggression,
            'self_neglect'  => $this->self_neglect,
            'vulnerability_from_others'  => $this->vulnerability_from_others,
            'indication_of_physical_emotional_abuse'  => $this->indication_of_physical_emotional_abuse,
            'is_full_mobile'  => $this->is_full_mobile,
            'staff' => new EmployeeChartResource($this->staff),
            'client' => new ClientChartResource($this->client),
            'use_walking_aid'  => $this->use_walking_aid,
            'is_wheel_chair_dependant'  => $this->is_wheel_chair_dependant,
            'need_assistance_of_one'  => $this->need_assistance_of_one,
            'need_assistance_of_two'  => $this->need_assistance_of_two,
            'is_fully_dependant'  => $this->is_fully_dependant,
            'has_demantia_frail'  => $this->has_demantia_frail,
            'has_high_blood_pressure'  => $this->has_high_blood_pressure,
            'has_poor_circulation'  => $this->has_poor_circulation,
            'has_cva_tia'  => $this->has_cva_tia,
            'has_osteo_rheumatoid_arthritis'  => $this->has_osteo_rheumatoid_arthritis,
            'has_osteoporosis'  => $this->has_osteoporosis,
            'has_poor_vision'  => $this->has_poor_vision,
            'has_poor_hearing'  => $this->has_poor_hearing,
            'has_diabetes'  => $this->has_diabetes,
            'has_amputee'  => $this->has_amputee,
            'has_history_of_falls'  => $this->has_history_of_falls,
            'admitted_for_investigation'  => $this->admitted_for_investigation,
            'has_catheter'  => $this->has_catheter,
            'has_inco_urine'  => $this->has_inco_urine,
            'has_inco_faeces'  => $this->has_inco_faeces,
            'has_incontinent_doubly'  => $this->has_incontinent_doubly,
            'requires_assistance'  => $this->requires_assistance,
            'uses_diuretics'  => $this->uses_diuretics,
            'uses_sedatives'  => $this->uses_sedatives,
            'uses_tranquilisers'  => $this->uses_tranquilisers,
            'uses_anti_hypertensive'  => $this->uses_anti_hypertensive,
            'uses_reg_aperient'  => $this->uses_reg_aperient,
            'uses_hypoglycaemic_agents'  => $this->uses_hypoglycaemic_agents,
            'drink_alcohol'  => $this->drink_alcohol,
            'resident_height'  => $this->resident_height,
            'resident_weight'  => $this->resident_weight,
            'info_comprehension'  => $this->info_comprehension,
            'info_behavior'  => $this->info_behavior,
            'info_disability'  => $this->info_disability,
            'handling_pain'  => $this->handling_pain,
            'handling_skin'  => $this->handling_skin,
            'handling_other'  => $this->handling_other,
            'movement_walking'  => $this->movement_walking,
            'movement_standing'  => $this->movement_standing,
            'movement_using_toilet'  => $this->movement_using_toilet,
            'movement_going_to_bed'  => $this->movement_going_to_bed,
            'movement_getting_from_bed'  => $this->movement_getting_from_bed,
            'movement_on_bed'  => $this->movement_on_bed,
            'visit_type'  => $this->visit_type,
            'visit_location'  => $this->visit_location,
            'visitor_name'  => $this->visitor_name,
            'bowel_type'  => $this->bowel_type,
            'weight_grams'  => $this->weight_grams,
            'weight_stone'  => $this->weight_stone,
            'food_period'  => $this->food_period,
            'food_type'  => $this->food_type,
            'review_type'  => $this->review_type,
            'service_user_participant'  => $this->service_user_participant,
            'temperature' => $this->temperature,
            'pulse' => $this->pulse,
            'blood_pressure_systolic' => $this->blood_pressure_systolic,
            'blood_pressure_diastolic' => $this->blood_pressure_diastolic,
            'blood_sugar' => $this->blood_sugar,
            'oxygen_saturation' => $this->oxygen_saturation,
            'stool_observed' => $this->stool_observed,
            'respiration' => $this->respiration,
            'antecedent_event' => $this->antecedent_event,
            'medicine_name' => $this->medicine_name,
            'medication_type' => $this->medication_type,
            'medication_unit' => $this->medication_unit,
            'dosage_morning' => $this->dosage_morning,
            'dosage_morning_when' => $this->dosage_morning_when,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ]);
    }
}
