<?php

namespace App\Dto;

class EventType
{
    const APPLICATION_APPROVED = "APPLICATION_APPROVED";
    const APPLICATION_REJECTED = "APPLICATION_REJECTED";
    const APPLICATION_NEW = "APPLICATION_NEW";
    const NEW_ACCOUNT = "NEW_ACCOUNT";
    const NEW_STAFF = "NEW_STAFF";
    const INCIDENT = "INCIDENT";
    const SUCCESSFUL_REGISTRATION = "SUCCESSFUL_REGISTRATION";
    const PASSWORD_RESET = "PASSWORD_RESET";
    const ACCOUNT_ACTIVATED = "ACCOUNT_ACTIVATED";
    const ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED";
    const DEATH_RECORD = "DEATH_RECORD";
    const DOCUMENT_CLIENT_CREATED = "DOCUMENT_CLIENT_CREATED";
    const DOCUMENT_CLIENT_UPDATE = "DOCUMENT_CLIENT_UPDATE";
    const DOCUMENT_STAFF_CREATED = "DOCUMENT_STAFF_CREATED";
    const DOCUMENT_STAFF_UPDATE = "DOCUMENT_STAFF_UPDATE";
    const FAMILY_FRIEND_CREATED = "FAMILY_FRIEND_CREATED";
    const FAMILY_FRIEND_UPDATED = "FAMILY_FRIEND_UPDATED";
    const HEALTH_ISSUE_ADMIN = "HEALTH_ISSUE_ADMIN";
    const HEALTH_ISSUE_ADMIN_UPDATED = "HEALTH_ISSUE_ADMIN_UPDATED";
    const HEALTH_ISSUE_FRIEND = "HEALTH_ISSUE_FRIEND";
    const HEALTH_ISSUE_FRIEND_UPDATED = "HEALTH_ISSUE_FRIEND_UPDATED";
    const INDIVIDUAL_PAY_RUN = "INDIVIDUAL_PAY_RUN";
    const INVOICE_CREATED = "INVOICE_CREATED";
    const LOW_STOCK = "LOW_STOCK";
    const MEDICAL_VISIT_ADMIN = "MEDICAL_VISIT_ADMIN";
    const MEDICAL_VISIT_FRIEND = "MEDICAL_VISIT_FRIEND";
    const MEDICATION_ADMIN = "MEDICATION_ADMIN";
    const MEDICATION_FRIEND = "MEDICATION_FRIEND";
    const ACCOUNT_BY_ADMIN = "ACCOUNT_BY_ADMIN";
    const PRESCRIPTION_ADMIN_CREATED = "PRESCRIPTION_ADMIN_CREATED";
    const PRESCRIPTION_ADMIN_UPDATED = "PRESCRIPTION_ADMIN_UPDATED";
    const PRESCRIPTION_FRIEND_CREATED = "PRESCRIPTION_FRIEND_CREATED";
    const PRESCRIPTION_FRIEND_UPDATED = "PRESCRIPTION_FRIEND_UPDATED";
    const STAFF_ASSIGNMENT_CREATED = "STAFF_ASSIGNMENT_CREATED";
    const STAFF_ASSIGNMENT_UPDATED = "STAFF_ASSIGNMENT_UPDATED";
    const PROCEDURE_ADMIN = "PROCEDURE_ADMIN";
    const PROCEDURE_FRIEND = "PROCEDURE_FRIEND";
    const RECEIPT = "RECEIPT";
}
